### ISSUE TITLE
Company completion popup sorted alphabetically

### ISSUE THREAD

**Issue by millejoh** [mfiano/common-lisp-sly#1]
For some reason in my spacemacs setup the candidates completion popup/tooltip generated by company is sorted alphabetically instead of by completion score.

Not sure how you would recreate this issue, but I've found it goes away if I comment out the `common-lisp-sly/post-init-company` function in `packages.el`.

Thanks for putting together this configuration, it made for a nice introduction to sly!

**Comment by mfiano** [comment]
Commenting out that function would disable company-mode completely. You must have some other Spacemacs configuration at play here in order for this to work for you.
