### ISSUE TITLE
Key bind in readme is wrong?

### ISSUE THREAD

**Issue by cuichaox** [mfiano/common-lisp-sly#3]

**Comment by mfiano** [comment]
What exactly is wrong?

**Comment by cuichaox** [comment]
I am getting  'sly-apropos   binding to 'C-c C-d C-a' (not 'SPC m h a‘).  Am I missing something?

**Comment by mfiano** [comment]
That is correct and I can't reproduce this. Please ensure you are on the tip of the Spacemacs develop branch and try again. If you are still having issues, please let us know what describe-key shows for that bindings, and any other helpful information you can provide and re-open this issue.

**Comment by cuichaox** [comment]
Thank you very mutch. I am confused and finally figured it out. in edit style of 'emacs,  The default setting of Major mode leader key  is "C-M-m",  is not The "<leader> m" ( "M-m m").
